inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

AllCops:
  TargetRubyVersion: 2.6.4

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: normal

Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: around 
