AllCops:
  Exclude:
    - 'public/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Layout/AccessModifierIndentation:
  Exclude:

Layout/ArgumentAlignment:
  Exclude:

Layout/EmptyLineAfterGuardClause:
  Exclude:

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - 'config/environments/development.rb'
    - 'config/environments/production.rb'

Metrics/AbcSize:
  Max: 18

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 13

Metrics/PerceivedComplexity:
  Max: 9

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/channels/application_cable/connection_test.rb'
    - 'test/test_helper.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'

Style/ExpandPathArguments:
  Exclude:

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Exclude:

Style/PerlBackrefs:
  Exclude:

Style/RedundantBegin:
  Exclude:

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/StderrPuts:
  Exclude:

Style/StringLiterals:
  Exclude:
    - 'config/environments/production.rb'
    - 'config/puma.rb'
    - 'config/spring.rb'
    - 'spec/rails_helper.rb'
    - 'test/application_system_test_case.rb'
    - 'test/channels/application_cable/connection_test.rb'

Style/SymbolArray:
  EnforcedStyle: brackets

Layout/LineLength:
  Max: 120
